import { NextRequest, NextResponse } from 'next/server';
import { API_URL, type ApiEnvelope } from '../../../../../../../lib/api';
import { getAccessTokenFromCookies } from '../../../../../../../lib/auth-session';
function badRequest(message: string, status = 400) { return NextResponse.json({ ok: false, error: { message } }, { status }); }
const defaults = { apiUrl: API_URL, readAccessToken: getAccessTokenFromCookies, fetchImpl: fetch };
let deps = { ...defaults };
export function setUserBillingOverrideRouteDependenciesForTests(overrides: Partial<typeof defaults>) { deps = { ...deps, ...overrides }; }
export function resetUserBillingOverrideRouteDependenciesForTests() { deps = { ...defaults }; }
export async function PATCH(request: NextRequest, context: { params: Promise<{ userId: string }> }) { const accessToken = await deps.readAccessToken(); if (!accessToken) return badRequest('Sign in to update override.', 401); const { userId } = await context.params; const body = await request.json().catch(() => ({})); const response = await deps.fetchImpl(`${deps.apiUrl}/admin/billing/users/${encodeURIComponent(userId)}/override`, { method: 'PATCH', cache: 'no-store', headers: { authorization: `Bearer ${accessToken}`, 'content-type': 'application/json' }, body: JSON.stringify(body ?? {}) }); const payload = (await response.json().catch(() => null)) as ApiEnvelope<unknown> | null; if (!response.ok || !payload?.ok) return badRequest('Unable to update override right now.', response.status || 500); return NextResponse.json({ ok: true, data: payload.data }, { status: response.status }); }
export async function DELETE(_request: NextRequest, context: { params: Promise<{ userId: string }> }) { const accessToken = await deps.readAccessToken(); if (!accessToken) return badRequest('Sign in to clear override.', 401); const { userId } = await context.params; const response = await deps.fetchImpl(`${deps.apiUrl}/admin/billing/users/${encodeURIComponent(userId)}/override`, { method: 'DELETE', cache: 'no-store', headers: { authorization: `Bearer ${accessToken}` } }); const payload = (await response.json().catch(() => null)) as ApiEnvelope<unknown> | null; if (!response.ok || !payload?.ok) return badRequest('Unable to clear override right now.', response.status || 500); return NextResponse.json({ ok: true, data: payload.data }, { status: response.status }); }
