export const apiModules = [
  'auth',
  'users',
  'workspaces',
  'permissions',
  'billing',
  'entitlements',
  'feature-flags',
  'remote-config',
  'extension-compatibility',
  'ai',
  'usage',
  'audit',
  'support',
] as const;
