import { type ApiRouteDefinition } from '@quizmind/contracts';

export const apiRoutes: ApiRouteDefinition[] = [
  {
    method: 'GET',
    path: '/health',
    summary: 'Return runtime status, configured infrastructure, and queue readiness.',
  },
  {
    method: 'GET',
    path: '/ready',
    summary: 'Return strict deploy readiness status (connected mode + env validation + infra reachability).',
  },
  {
    method: 'GET',
    path: '/foundation',
    summary: 'Return monorepo foundation metadata, route inventory, and platform capabilities.',
  },
  {
    method: 'POST',
    path: '/auth/register',
    summary: 'Register a new user and create a session immediately.',
  },
  {
    method: 'POST',
    path: '/auth/login',
    summary: 'Authenticate a user and issue access + refresh tokens.',
  },
  {
    method: 'POST',
    path: '/auth/refresh',
    summary: 'Rotate a refresh token and issue a new access + refresh token pair.',
  },
  {
    method: 'POST',
    path: '/auth/forgot-password',
    summary: 'Accept a password reset request and send a reset email when the account exists.',
  },
  {
    method: 'POST',
    path: '/auth/reset-password',
    summary: 'Redeem a password reset token, rotate sessions, and issue a fresh auth session.',
  },
  {
    method: 'POST',
    path: '/auth/logout',
    summary: 'Revoke the current session by refresh token or bearer access token.',
  },
  {
    method: 'POST',
    path: '/auth/logout-all',
    summary: 'Revoke all active sessions for the current user.',
  },
  {
    method: 'GET',
    path: '/auth/me',
    summary: 'Return the current session principal and workspace memberships.',
  },
  {
    method: 'GET',
    path: '/auth/sessions',
    summary: 'List active sessions for the current user and flag the current browser session.',
  },
  {
    method: 'GET',
    path: '/workspaces',
    summary: 'List workspaces accessible to the current user.',
    permission: 'workspaces:read',
  },
  {
    method: 'GET',
    path: '/workspaces/:id',
    summary: 'Return workspace details and access state for a specific workspace.',
    permission: 'workspaces:read',
  },
  {
    method: 'GET',
    path: '/user/profile',
    summary: 'Return profile details for the authenticated user account.',
  },
  {
    method: 'PATCH',
    path: '/user/profile',
    summary: 'Update mutable user profile settings such as display name, avatar, locale, and timezone.',
  },
  {
    method: 'GET',
    path: '/usage/summary',
    summary: 'Return quota counters, extension installations, and recent usage activity for a workspace.',
    permission: 'usage:read',
  },
  {
    method: 'GET',
    path: '/usage/history',
    summary: 'Return filtered usage activity history for telemetry, workspace activity, and AI proxy streams.',
    permission: 'usage:read',
  },
  {
    method: 'POST',
    path: '/admin/usage/export',
    summary: 'Export usage snapshot data for a workspace as JSON or CSV.',
    permission: 'usage:export',
  },
  {
    method: 'POST',
    path: '/billing/webhooks/yookassa',
    summary: 'Persist and enqueue YooKassa billing webhook deliveries.',
  },
  {
    method: 'POST',
    path: '/extension/bootstrap',
    summary: 'Resolve compatibility, feature flags, and remote config for an extension installation.',
  },
  {
    method: 'GET',
    path: '/extension/installations',
    summary: 'List extension installations, compatibility state, and active installation sessions for a workspace.',
    permission: 'installations:read',
  },
  {
    method: 'POST',
    path: '/extension/installations/disconnect',
    summary: 'Revoke active installation sessions for a workspace installation so the extension must reconnect (operator reason required).',
    permission: 'installations:write',
  },
  {
    method: 'POST',
    path: '/extension/installations/rotate-session',
    summary: 'Rotate the active installation session token for a workspace installation and revoke previous sessions (operator reason required).',
    permission: 'installations:write',
  },
  {
    method: 'POST',
    path: '/extension/installations/bind',
    summary: 'Bind an authenticated extension installation to a platform user and issue a short-lived installation session.',
  },
  {
    method: 'POST',
    path: '/extension/installations/session/refresh',
    summary: 'Silently refresh an installation session token using the current token, without requiring user re-login.',
  },
  {
    method: 'POST',
    path: '/extension/bootstrap/v2',
    summary: 'Resolve the managed-client bootstrap payload for an installation-authenticated extension session.',
  },
  {
    method: 'POST',
    path: '/extension/usage-events',
    summary: 'Ingest extension usage and telemetry events.',
  },
  {
    method: 'POST',
    path: '/extension/usage-events/v2',
    summary: 'Ingest extension telemetry using an installation-authenticated session.',
  },
  {
    method: 'GET',
    path: '/extension/ai/models',
    summary: 'Return extension-managed AI model catalog for installation-authenticated runtime clients.',
  },
  {
    method: 'POST',
    path: '/extension/ai/answer',
    summary: 'Proxy extension answer requests through the installation-authenticated AI runtime bridge.',
  },
  {
    method: 'POST',
    path: '/extension/ai/chat',
    summary: 'Proxy extension chat requests through the installation-authenticated AI runtime bridge.',
  },
  {
    method: 'POST',
    path: '/extension/ai/screenshot',
    summary: 'Proxy extension screenshot requests through the installation-authenticated AI runtime bridge.',
  },
  {
    method: 'POST',
    path: '/extension/ai/multicheck',
    summary: 'Proxy extension multicheck requests through the installation-authenticated AI runtime bridge.',
  },
  {
    method: 'POST',
    path: '/ai/proxy',
    summary: 'Proxy AI chat-completion requests with policy, quota, and BYOK enforcement.',
  },
  {
    method: 'GET',
    path: '/ai/models',
    summary: 'Return AI model availability for the current workspace and provider policy.',
  },
  {
    method: 'GET',
    path: '/user/api-keys',
    summary: 'List user-owned API keys for BYOK without returning decrypted provider secrets.',
    permission: 'credentials:read',
  },
  {
    method: 'POST',
    path: '/user/api-keys',
    summary: 'Create a user-owned encrypted API key for BYOK routing in the selected workspace context.',
    permission: 'credentials:write',
  },
  {
    method: 'DELETE',
    path: '/user/api-keys/:id',
    summary: 'Revoke a previously saved user API key while preserving audit history.',
    permission: 'credentials:rotate',
  },
  {
    method: 'POST',
    path: '/user/api-keys/:id/test',
    summary: 'Run a BYOK validation pass for a stored user API key and persist the latest validation status.',
    permission: 'credentials:rotate',
  },
  {
    method: 'GET',
    path: '/providers/catalog',
    summary: 'Return the AI provider registry and model catalog available to the control plane.',
  },
  {
    method: 'GET',
    path: '/admin/providers',
    summary: 'Return admin governance visibility for platform and workspace AI provider credentials.',
    permission: 'ai_providers:manage',
  },
  {
    method: 'POST',
    path: '/admin/providers/policy',
    summary: 'Update the persisted AI provider policy for the global scope or a selected workspace scope.',
    permission: 'ai_providers:manage',
  },
  {
    method: 'POST',
    path: '/admin/providers/policy/reset',
    summary: 'Remove a workspace-specific AI provider policy override so the workspace inherits the global policy again.',
    permission: 'ai_providers:manage',
  },
  {
    method: 'GET',
    path: '/providers/credentials',
    summary: 'List provider credentials visible to the current user in the selected workspace context.',
    permission: 'credentials:read',
  },
  {
    method: 'POST',
    path: '/providers/credentials',
    summary: 'Create a new encrypted provider credential for user, workspace, or platform ownership.',
    permission: 'credentials:write',
  },
  {
    method: 'POST',
    path: '/providers/credentials/rotate',
    summary: 'Rotate an existing provider credential secret without exposing the raw key again.',
    permission: 'credentials:rotate',
  },
  {
    method: 'POST',
    path: '/providers/credentials/revoke',
    summary: 'Revoke a stored provider credential and keep its audit trail intact.',
    permission: 'credentials:rotate',
  },
  {
    method: 'GET',
    path: '/admin/users',
    summary: 'List users, their system roles, and workspace memberships.',
    permission: 'users:read',
  },
  {
    method: 'POST',
    path: '/admin/users/create',
    summary: 'Create a user account with initial system roles and workspace memberships.',
    permission: 'users:update',
  },
  {
    method: 'POST',
    path: '/admin/users/update-access',
    summary: 'Update a user access profile including system roles, workspace memberships, and suspension state.',
    permission: 'users:update',
  },
  {
    method: 'GET',
    path: '/admin/installations',
    summary: 'Inspect workspace-scoped extension installation fleet health, compatibility state, and installation token activity.',
    permission: 'installations:read',
  },
  {
    method: 'GET',
    path: '/admin/webhooks',
    summary: 'Inspect recent billing webhook deliveries, queue bindings, and retry eligibility for ops workflows.',
    permission: 'jobs:read',
  },
  {
    method: 'POST',
    path: '/admin/webhooks/retry',
    summary: 'Requeue a failed billing webhook delivery onto the billing-webhooks worker queue.',
    permission: 'jobs:retry',
  },
  {
    method: 'GET',
    path: '/admin/logs',
    summary: 'List audit, activity, security, and domain log streams for the selected workspace context.',
    permission: 'audit_logs:read',
  },
  {
    method: 'GET',
    path: '/admin/security',
    summary: 'Return a security-focused admin snapshot with filtered security events, findings, and hardening checkpoints.',
    permission: 'audit_logs:read',
  },
  {
    method: 'POST',
    path: '/admin/logs/export',
    summary: 'Export filtered audit, activity, security, and domain log entries as JSON or CSV.',
    permission: 'audit_logs:export',
  },
  {
    method: 'GET',
    path: '/admin/feature-flags',
    summary: 'List feature flags and rollout state.',
    permission: 'feature_flags:read',
  },
  {
    method: 'GET',
    path: '/admin/compatibility',
    summary: 'List recent extension compatibility rules that drive bootstrap verdicts.',
    permission: 'compatibility_rules:manage',
  },
  {
    method: 'POST',
    path: '/admin/compatibility/publish',
    summary: 'Publish a new extension compatibility rule so the newest verdict governs future bootstrap requests.',
    permission: 'compatibility_rules:manage',
  },
  {
    method: 'POST',
    path: '/admin/feature-flags/update',
    summary: 'Update a feature flag definition, rollout, and targeting allow-lists.',
    permission: 'feature_flags:write',
  },
  {
    method: 'GET',
    path: '/admin/remote-config',
    summary: 'Return active remote config layers plus a resolved preview for the current workspace context.',
    permission: 'remote_config:publish',
  },
  {
    method: 'POST',
    path: '/admin/remote-config/publish',
    summary: 'Publish a remote config version.',
    permission: 'remote_config:publish',
  },
  {
    method: 'POST',
    path: '/admin/remote-config/activate',
    summary: 'Activate a previously published remote config version for rollback or re-promotion.',
    permission: 'remote_config:publish',
  },
  {
    method: 'GET',
    path: '/support/impersonation-sessions',
    summary: 'List recent support impersonation sessions with actor, target, and workspace context.',
    permission: 'support:impersonate',
  },
  {
    method: 'GET',
    path: '/support/tickets',
    summary: 'List support tickets with queue filters, named presets, requester context, and recent workflow history.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/impersonation',
    summary: 'Start a support impersonation session and emit audit + security logs.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/tickets/update',
    summary: 'Assign a support ticket, update workflow status, and save handoff metadata.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/tickets/preset-favorite',
    summary: 'Persist or remove personal support queue preset favorites for the current operator.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/impersonation/end',
    summary: 'End an active support impersonation session, persist an optional close reason, and emit audit + security logs.',
    permission: 'support:impersonate',
  },
] as const;
