import { type ApiRouteDefinition } from '@quizmind/contracts';

export const apiRoutes: ApiRouteDefinition[] = [
  {
    method: 'GET',
    path: '/health',
    summary: 'Return runtime status, configured infrastructure, and queue readiness.',
  },
  {
    method: 'GET',
    path: '/foundation',
    summary: 'Return monorepo foundation metadata, route inventory, and platform capabilities.',
  },
  {
    method: 'POST',
    path: '/auth/register',
    summary: 'Register a new user, create a session, and send an email verification link.',
  },
  {
    method: 'POST',
    path: '/auth/login',
    summary: 'Authenticate a user and issue access + refresh tokens.',
  },
  {
    method: 'POST',
    path: '/auth/refresh',
    summary: 'Rotate a refresh token and issue a new access + refresh token pair.',
  },
  {
    method: 'POST',
    path: '/auth/forgot-password',
    summary: 'Accept a password reset request and send a reset email when the account exists.',
  },
  {
    method: 'POST',
    path: '/auth/reset-password',
    summary: 'Redeem a password reset token, rotate sessions, and issue a fresh auth session.',
  },
  {
    method: 'POST',
    path: '/auth/logout',
    summary: 'Revoke the current session by refresh token or bearer access token.',
  },
  {
    method: 'POST',
    path: '/auth/logout-all',
    summary: 'Revoke all active sessions for the current user.',
  },
  {
    method: 'GET',
    path: '/auth/me',
    summary: 'Return the current session principal and workspace memberships.',
  },
  {
    method: 'GET',
    path: '/auth/sessions',
    summary: 'List active sessions for the current user and flag the current browser session.',
  },
  {
    method: 'GET',
    path: '/auth/verify-email',
    summary: 'Verify a pending email verification token and mark the email as confirmed.',
  },
  {
    method: 'GET',
    path: '/workspaces',
    summary: 'List workspaces accessible to the current user.',
    permission: 'workspaces:read',
  },
  {
    method: 'GET',
    path: '/billing/plans',
    summary: 'Return the public billing plan catalog, prices, and entitlements for pricing surfaces.',
  },
  {
    method: 'GET',
    path: '/billing/subscription',
    summary: 'Return current subscription, plan, and entitlement state for a workspace.',
    permission: 'subscriptions:read',
  },
  {
    method: 'GET',
    path: '/usage/summary',
    summary: 'Return quota counters, extension installations, and recent usage activity for a workspace.',
    permission: 'usage:read',
  },
  {
    method: 'POST',
    path: '/admin/usage/export',
    summary: 'Export usage snapshot data for a workspace as JSON or CSV.',
    permission: 'usage:export',
  },
  {
    method: 'GET',
    path: '/billing/invoices',
    summary: 'Return billing invoices for the current workspace, ordered from newest to oldest.',
    permission: 'subscriptions:read',
  },
  {
    method: 'GET',
    path: '/billing/invoices/:invoiceId/pdf',
    summary: 'Resolve the Stripe-hosted PDF or invoice page for a workspace invoice export.',
    permission: 'subscriptions:read',
  },
  {
    method: 'POST',
    path: '/billing/checkout',
    summary: 'Create a Stripe Checkout Session and return a hosted redirect URL for a workspace upgrade.',
    permission: 'subscriptions:update',
  },
  {
    method: 'GET',
    path: '/billing/portal',
    summary: 'Create a Stripe Customer Portal session for payment method and subscription management.',
    permission: 'subscriptions:update',
  },
  {
    method: 'POST',
    path: '/billing/cancel',
    summary: 'Mark the current Stripe subscription to cancel at period end for a workspace.',
    permission: 'subscriptions:update',
  },
  {
    method: 'POST',
    path: '/billing/resume',
    summary: 'Undo a scheduled subscription cancellation for a workspace before the billing period ends.',
    permission: 'subscriptions:update',
  },
  {
    method: 'POST',
    path: '/billing/webhooks/stripe',
    summary: 'Verify, persist, and enqueue Stripe billing webhook deliveries.',
  },
  {
    method: 'POST',
    path: '/billing/webhooks/yookassa',
    summary: 'Persist and enqueue YooKassa billing webhook deliveries.',
  },
  {
    method: 'POST',
    path: '/extension/bootstrap',
    summary: 'Resolve compatibility, feature flags, and remote config for an extension installation.',
  },
  {
    method: 'GET',
    path: '/extension/installations',
    summary: 'List extension installations, compatibility state, and active installation sessions for a workspace.',
    permission: 'installations:read',
  },
  {
    method: 'POST',
    path: '/extension/installations/disconnect',
    summary: 'Revoke active installation sessions for a workspace installation so the extension must reconnect.',
    permission: 'installations:write',
  },
  {
    method: 'POST',
    path: '/extension/installations/rotate-session',
    summary: 'Rotate the active installation session token for a workspace installation and revoke previous sessions.',
    permission: 'installations:write',
  },
  {
    method: 'POST',
    path: '/extension/installations/bind',
    summary: 'Bind an authenticated extension installation to a platform user and issue a short-lived installation session.',
  },
  {
    method: 'POST',
    path: '/extension/bootstrap/v2',
    summary: 'Resolve the managed-client bootstrap payload for an installation-authenticated extension session.',
  },
  {
    method: 'POST',
    path: '/extension/usage-events',
    summary: 'Ingest extension usage and telemetry events.',
  },
  {
    method: 'POST',
    path: '/extension/usage-events/v2',
    summary: 'Ingest extension telemetry using an installation-authenticated session.',
  },
  {
    method: 'POST',
    path: '/ai/proxy',
    summary: 'Proxy AI chat-completion requests with policy, quota, and BYOK enforcement.',
  },
  {
    method: 'GET',
    path: '/providers/catalog',
    summary: 'Return the AI provider registry and model catalog available to the control plane.',
  },
  {
    method: 'GET',
    path: '/admin/providers',
    summary: 'Return admin governance visibility for platform and workspace AI provider credentials.',
    permission: 'ai_providers:manage',
  },
  {
    method: 'POST',
    path: '/admin/providers/policy',
    summary: 'Update the persisted AI provider policy for the global scope or a selected workspace scope.',
    permission: 'ai_providers:manage',
  },
  {
    method: 'POST',
    path: '/admin/providers/policy/reset',
    summary: 'Remove a workspace-specific AI provider policy override so the workspace inherits the global policy again.',
    permission: 'ai_providers:manage',
  },
  {
    method: 'GET',
    path: '/providers/credentials',
    summary: 'List provider credentials visible to the current user in the selected workspace context.',
    permission: 'credentials:read',
  },
  {
    method: 'POST',
    path: '/providers/credentials',
    summary: 'Create a new encrypted provider credential for user, workspace, or platform ownership.',
    permission: 'credentials:write',
  },
  {
    method: 'POST',
    path: '/providers/credentials/rotate',
    summary: 'Rotate an existing provider credential secret without exposing the raw key again.',
    permission: 'credentials:rotate',
  },
  {
    method: 'POST',
    path: '/providers/credentials/revoke',
    summary: 'Revoke a stored provider credential and keep its audit trail intact.',
    permission: 'credentials:rotate',
  },
  {
    method: 'GET',
    path: '/admin/users',
    summary: 'List users, their system roles, and workspace memberships.',
    permission: 'users:read',
  },
  {
    method: 'GET',
    path: '/admin/installations',
    summary: 'Inspect workspace-scoped extension installation fleet health, compatibility state, and installation token activity.',
    permission: 'installations:read',
  },
  {
    method: 'GET',
    path: '/admin/webhooks',
    summary: 'Inspect recent billing webhook deliveries, queue bindings, and retry eligibility for ops workflows.',
    permission: 'jobs:read',
  },
  {
    method: 'POST',
    path: '/admin/webhooks/retry',
    summary: 'Requeue a failed billing webhook delivery onto the billing-webhooks worker queue.',
    permission: 'jobs:retry',
  },
  {
    method: 'GET',
    path: '/admin/logs',
    summary: 'List audit, activity, security, and domain log streams for the selected workspace context.',
    permission: 'audit_logs:read',
  },
  {
    method: 'POST',
    path: '/admin/logs/export',
    summary: 'Export filtered audit, activity, security, and domain log entries as JSON or CSV.',
    permission: 'audit_logs:export',
  },
  {
    method: 'GET',
    path: '/admin/plans',
    summary: 'Return the full billing plan catalog, including inactive plans, prices, and entitlements for admin control-plane management.',
    permission: 'plans:manage',
  },
  {
    method: 'POST',
    path: '/admin/plans/update',
    summary: 'Update a billing plan catalog entry, including active state, prices, and entitlements.',
    permission: 'plans:manage',
  },
  {
    method: 'GET',
    path: '/admin/feature-flags',
    summary: 'List feature flags and rollout state.',
    permission: 'feature_flags:read',
  },
  {
    method: 'GET',
    path: '/admin/compatibility',
    summary: 'List recent extension compatibility rules that drive bootstrap verdicts.',
    permission: 'compatibility_rules:manage',
  },
  {
    method: 'POST',
    path: '/admin/compatibility/publish',
    summary: 'Publish a new extension compatibility rule so the newest verdict governs future bootstrap requests.',
    permission: 'compatibility_rules:manage',
  },
  {
    method: 'POST',
    path: '/admin/feature-flags/update',
    summary: 'Update a feature flag definition, rollout, and targeting allow-lists.',
    permission: 'feature_flags:write',
  },
  {
    method: 'GET',
    path: '/admin/remote-config',
    summary: 'Return active remote config layers plus a resolved preview for the current workspace context.',
    permission: 'remote_config:publish',
  },
  {
    method: 'POST',
    path: '/admin/remote-config/publish',
    summary: 'Publish a remote config version.',
    permission: 'remote_config:publish',
  },
  {
    method: 'POST',
    path: '/admin/remote-config/activate',
    summary: 'Activate a previously published remote config version for rollback or re-promotion.',
    permission: 'remote_config:publish',
  },
  {
    method: 'GET',
    path: '/support/impersonation-sessions',
    summary: 'List recent support impersonation sessions with actor, target, and workspace context.',
    permission: 'support:impersonate',
  },
  {
    method: 'GET',
    path: '/support/tickets',
    summary: 'List support tickets with queue filters, named presets, requester context, and recent workflow history.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/impersonation',
    summary: 'Start a support impersonation session and emit audit + security logs.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/tickets/update',
    summary: 'Assign a support ticket, update workflow status, and save handoff metadata.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/tickets/preset-favorite',
    summary: 'Persist or remove personal support queue preset favorites for the current operator.',
    permission: 'support:impersonate',
  },
  {
    method: 'POST',
    path: '/support/impersonation/end',
    summary: 'End an active support impersonation session, persist an optional close reason, and emit audit + security logs.',
    permission: 'support:impersonate',
  },
] as const;
